### ISSUE TITLE
Errors due to inverting 0 matrices

### ISSUE THREAD

**Issue by amrhamedp** [atomistic-machine-learning/dtnn#1]
Hello  I have several errors while trying to run this code:

INFO - Starting at iteration 0 / 5000000
INFO - Saved checkpoint at iteration 0 / 5000000
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Input is not invertible.
	 [[Node: DTNN_2/preprocessing/distance/MatrixInverse = MatrixInverse[T=DT_FLOAT, adjoint=false, _device="/job:localhost/replica:0/task:0/cpu:0"](fifo_queue_1_Dequeue:2)]]

Caused by op 'DTNN_2/preprocessing/distance/MatrixInverse', defined at:
  File "train_dtnn_gdb9.py", line 201, in <module>
    main(args)
  File "train_dtnn_gdb9.py", line 134, in main
    summary_interval=1000
  File "/media/cresset/DATA/instructions/31DTNN/dtnn2/dtnn/dtnn/train.py", line 66, in early_stopping
    num_batch_threads=1
  File "/media/cresset/DATA/instructions/31DTNN/dtnn2/dtnn/dtnn/core.py", line 119, in get_output
    features = self._preprocessor(features)
  File "/media/cresset/DATA/instructions/31DTNN/dtnn2/dtnn/dtnn/models/dtnn.py", line 60, in _preprocessor
    positions, cell, pbc, self.cutoff
  File "/media/cresset/DATA/instructions/31DTNN/dtnn2/dtnn/dtnn/atoms.py", line 8, in interatomic_distances
    icell = tf.matrix_inverse(cell)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/ops/gen_linalg_ops.py", line 330, in matrix_inverse
    name=name)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Input is not invertible.
	 [[Node: DTNN_2/preprocessing/distance/MatrixInverse = MatrixInverse[T=DT_FLOAT, adjoint=false, _device="/job:localhost/replica:0/task:0/cpu:0"](fifo_queue_1_Dequeue:2)]]

INFO - Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Input is not invertible.
	 [[Node: DTNN_2/preprocessing/distance/MatrixInverse = MatrixInverse[T=DT_FLOAT, adjoint=false, _device="/job:localhost/replica:0/task:0/cpu:0"](fifo_queue_1_Dequeue:2)]]

Caused by op 'DTNN_2/preprocessing/distance/MatrixInverse', defined at:
  File "train_dtnn_gdb9.py", line 201, in <module>
    main(args)
  File "train_dtnn_gdb9.py", line 134, in main
    summary_interval=1000
  File "/media/cresset/DATA/instructions/31DTNN/dtnn2/dtnn/dtnn/train.py", line 66, in early_stopping
    num_batch_threads=1
  File "/media/cresset/DATA/instructions/31DTNN/dtnn2/dtnn/dtnn/core.py", line 119, in get_output
    features = self._preprocessor(features)
  File "/media/cresset/DATA/instructions/31DTNN/dtnn2/dtnn/dtnn/models/dtnn.py", line 60, in _preprocessor
    positions, cell, pbc, self.cutoff
  File "/media/cresset/DATA/instructions/31DTNN/dtnn2/dtnn/dtnn/atoms.py", line 8, in interatomic_distances
    icell = tf.matrix_inverse(cell)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/ops/gen_linalg_ops.py", line 330, in matrix_inverse
    name=name)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Input is not invertible.
	 [[Node: DTNN_2/preprocessing/distance/MatrixInverse = MatrixInverse[T=DT_FLOAT, adjoint=false, _device="/job:localhost/replica:0/task:0/cpu:0"](fifo_queue_1_Dequeue:2)]]

W tensorflow/core/kernels/queue_base.cc:302] _0_fifo_queue: Skipping cancelled dequeue attempt with queue not closed
W tensorflow/core/kernels/queue_base.cc:302] _0_fifo_queue: Skipping cancelled dequeue attempt with queue not closed
W tensorflow/core/kernels/queue_base.cc:302] _0_fifo_queue: Skipping cancelled dequeue attempt with queue not closed
W tensorflow/core/kernels/queue_base.cc:302] _0_fifo_queue: Skipping cancelled dequeue attempt with queue not closed
INFO - Saving chkpoint...
Traceback (most recent call last):
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/media/cresset/DATA/instructions/31DTNN/dtnn2/dtnn/dtnn/data.py", line 235, in _run
    sess.run(self.enqueue_op, feed_dict=fdict)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 903, in _run
    raise RuntimeError('Attempted to use a closed Session.')
RuntimeError: Attempted to use a closed Session.

    status, run_metadata)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/media/cresset/DATA/instructions/31DTNN/dtnn2/dtnn/dtnn/data.py", line 235, in _run
    sess.run(self.enqueue_op, feed_dict=fdict)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 903, in _run
    raise RuntimeError('Attempted to use a closed Session.')
RuntimeError: Attempted to use a closed Session.

    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.OutOfRangeError: PaddingFIFOQueue '_3_DTNN_2/batching/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1000, current size 0)
	 [[Node: DTNN_2/batching/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_BOOL, DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](DTNN_2/batching/batch/padding_fifo_queue, DTNN_2/batching/batch/n)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/cresset/DATA/instructions/31DTNN/dtnn2/dtnn/dtnn/train.py", line 169, in early_stopping
    _, train_sums = sess.run([train_op, train_summaries])
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: PaddingFIFOQueue '_3_DTNN_2/batching/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1000, current size 0)
	 [[Node: DTNN_2/batching/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_BOOL, DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](DTNN_2/batching/batch/padding_fifo_queue, DTNN_2/batching/batch/n)]]

Caused by op 'DTNN_2/batching/batch', defined at:
  File "train_dtnn_gdb9.py", line 201, in <module>
    main(args)
  File "train_dtnn_gdb9.py", line 134, in main
    summary_interval=1000
  File "/media/cresset/DATA/instructions/31DTNN/dtnn2/dtnn/dtnn/train.py", line 66, in early_stopping
    num_batch_threads=1
  File "/media/cresset/DATA/instructions/31DTNN/dtnn2/dtnn/dtnn/core.py", line 134, in get_output
    shapes=out_shapes, num_threads=num_batch_threads
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 872, in batch
    name=name)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 667, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/ops/data_flow_ops.py", line 458, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1310, in _queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

OutOfRangeError (see above for traceback): PaddingFIFOQueue '_3_DTNN_2/batching/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1000, current size 0)
	 [[Node: DTNN_2/batching/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_BOOL, DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](DTNN_2/batching/batch/padding_fifo_queue, DTNN_2/batching/batch/n)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_dtnn_gdb9.py", line 201, in <module>
    main(args)
  File "train_dtnn_gdb9.py", line 134, in main
    summary_interval=1000
  File "/media/cresset/DATA/instructions/31DTNN/dtnn2/dtnn/dtnn/train.py", line 226, in early_stopping
    chkpt_saver.save(sess, chkpt, i)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1363, in save
    {self.saver_def.filename_tensor_name: checkpoint_file})
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/cresset/anaconda2/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 903, in _run
    raise RuntimeError('Attempted to use a closed Session.')
RuntimeError: Attempted to use a closed Session.

**Comment by ktschuett** [comment]
Did you run the example script or did you try it with your own data? This looks like your ASE data has a zero matrix as cell. If you use the identity as cell, it should work. Otherwise, I will take a look tomorrow.

**Comment by Yuanpengli** [comment]
I added 
cell = cell + tf.diag(tf.constant(np.random.randn(3)*0.001,dtype=tf.float32)).
Then, the code can run in my cpu computer.
But, I don't know how it influence the result.
Thank U.

**Comment by ktschuett** [comment]
@Yuanpengli As long as you don't use periodic boundary conditions it should does not matter.
I guess ASE changed the default value of the cell in case of no PBC. I will add a check for that case.
